services:
  # Backend Flask API
  - type: web
    name: finvix-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: FLASK_APP
        value: backend/app.py
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: finvix-database
          property: connectionString
    healthCheckPath: /

databases:
  - name: finvix-database
    databaseName: finvix_db
    user: finvix_db_user
